/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.windows;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import programacion.dam.tarea7.beans.Articulo;
import programacion.dam.tarea7.services.CrudArticulos;

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {

    CrudArticulos articulosSrv = new CrudArticulos();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    private TableModel getTableModel() {
        List<Articulo> articulos = articulosSrv.listarArticulos();
        DefaultTableModel tableModel = new DefaultTableModel(
                new String[]{
                    "ID",
                    "DESCRIPCION",
                    "PRECIO",
                    "PRECIO",
                    "DESCUENTO",
                    "IVA"
                }
                , 0);
        if (articulos == null || articulos.isEmpty()) {
            return tableModel;
        }

        articulos.forEach((art) -> {
            tableModel.addRow(new Object[]{
                art.getCodArticulo(),
                art.getDescripcion(),
                art.getPrecio(),
                art.getDescuento(),
                art.getIva()
            });
        });
        return tableModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAbrir = new javax.swing.JMenuItem();
        menuGuardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuDatos = new javax.swing.JMenu();
        menuListados = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        menuAbrir.setText("Abrir");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(menuAbrir);

        menuGuardar.setText("Guardar");
        jMenu1.add(menuGuardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Alta");
        jMenuBar1.add(jMenu2);

        menuDatos.setText("Datos");
        jMenuBar1.add(menuDatos);

        menuListados.setText("Listados");
        jMenuBar1.add(menuListados);

        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSalirMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenu menuDatos;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenu menuListados;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
